# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import snakes_pb2 as snakes__pb2


class SnakesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSnake = channel.unary_unary(
                '/snakes.SnakesService/GetSnake',
                request_serializer=snakes__pb2.GetSnakeRequest.SerializeToString,
                response_deserializer=snakes__pb2.GetSnakeResponse.FromString,
                )
        self.CreateSnake = channel.unary_unary(
                '/snakes.SnakesService/CreateSnake',
                request_serializer=snakes__pb2.CreateSnakeRequest.SerializeToString,
                response_deserializer=snakes__pb2.CreateSnakeResponse.FromString,
                )


class SnakesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSnake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnakesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSnake': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnake,
                    request_deserializer=snakes__pb2.GetSnakeRequest.FromString,
                    response_serializer=snakes__pb2.GetSnakeResponse.SerializeToString,
            ),
            'CreateSnake': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnake,
                    request_deserializer=snakes__pb2.CreateSnakeRequest.FromString,
                    response_serializer=snakes__pb2.CreateSnakeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snakes.SnakesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SnakesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSnake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/snakes.SnakesService/GetSnake',
            snakes__pb2.GetSnakeRequest.SerializeToString,
            snakes__pb2.GetSnakeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSnake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/snakes.SnakesService/CreateSnake',
            snakes__pb2.CreateSnakeRequest.SerializeToString,
            snakes__pb2.CreateSnakeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
