# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snakes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snakes.proto',
  package='snakes',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csnakes.proto\x12\x06snakes\"\x1d\n\x0fGetSnakeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"Y\n\x10GetSnakeResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07pattern\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t\"3\n\x12\x43reateSnakeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07pattern\x18\x02 \x01(\t\"=\n\x13\x43reateSnakeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x9a\x01\n\rSnakesService\x12?\n\x08GetSnake\x12\x17.snakes.GetSnakeRequest\x1a\x18.snakes.GetSnakeResponse\"\x00\x12H\n\x0b\x43reateSnake\x12\x1a.snakes.CreateSnakeRequest\x1a\x1b.snakes.CreateSnakeResponse\"\x00\x62\x06proto3'
)




_GETSNAKEREQUEST = _descriptor.Descriptor(
  name='GetSnakeRequest',
  full_name='snakes.GetSnakeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='snakes.GetSnakeRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=53,
)


_GETSNAKERESPONSE = _descriptor.Descriptor(
  name='GetSnakeResponse',
  full_name='snakes.GetSnakeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='snakes.GetSnakeResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='snakes.GetSnakeResponse.pattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='snakes.GetSnakeResponse.success', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='snakes.GetSnakeResponse.error_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=144,
)


_CREATESNAKEREQUEST = _descriptor.Descriptor(
  name='CreateSnakeRequest',
  full_name='snakes.CreateSnakeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='snakes.CreateSnakeRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='snakes.CreateSnakeRequest.pattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=197,
)


_CREATESNAKERESPONSE = _descriptor.Descriptor(
  name='CreateSnakeResponse',
  full_name='snakes.CreateSnakeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='snakes.CreateSnakeResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='snakes.CreateSnakeResponse.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=260,
)

DESCRIPTOR.message_types_by_name['GetSnakeRequest'] = _GETSNAKEREQUEST
DESCRIPTOR.message_types_by_name['GetSnakeResponse'] = _GETSNAKERESPONSE
DESCRIPTOR.message_types_by_name['CreateSnakeRequest'] = _CREATESNAKEREQUEST
DESCRIPTOR.message_types_by_name['CreateSnakeResponse'] = _CREATESNAKERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSnakeRequest = _reflection.GeneratedProtocolMessageType('GetSnakeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSNAKEREQUEST,
  '__module__' : 'snakes_pb2'
  # @@protoc_insertion_point(class_scope:snakes.GetSnakeRequest)
  })
_sym_db.RegisterMessage(GetSnakeRequest)

GetSnakeResponse = _reflection.GeneratedProtocolMessageType('GetSnakeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSNAKERESPONSE,
  '__module__' : 'snakes_pb2'
  # @@protoc_insertion_point(class_scope:snakes.GetSnakeResponse)
  })
_sym_db.RegisterMessage(GetSnakeResponse)

CreateSnakeRequest = _reflection.GeneratedProtocolMessageType('CreateSnakeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESNAKEREQUEST,
  '__module__' : 'snakes_pb2'
  # @@protoc_insertion_point(class_scope:snakes.CreateSnakeRequest)
  })
_sym_db.RegisterMessage(CreateSnakeRequest)

CreateSnakeResponse = _reflection.GeneratedProtocolMessageType('CreateSnakeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATESNAKERESPONSE,
  '__module__' : 'snakes_pb2'
  # @@protoc_insertion_point(class_scope:snakes.CreateSnakeResponse)
  })
_sym_db.RegisterMessage(CreateSnakeResponse)



_SNAKESSERVICE = _descriptor.ServiceDescriptor(
  name='SnakesService',
  full_name='snakes.SnakesService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=263,
  serialized_end=417,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSnake',
    full_name='snakes.SnakesService.GetSnake',
    index=0,
    containing_service=None,
    input_type=_GETSNAKEREQUEST,
    output_type=_GETSNAKERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateSnake',
    full_name='snakes.SnakesService.CreateSnake',
    index=1,
    containing_service=None,
    input_type=_CREATESNAKEREQUEST,
    output_type=_CREATESNAKERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SNAKESSERVICE)

DESCRIPTOR.services_by_name['SnakesService'] = _SNAKESSERVICE

# @@protoc_insertion_point(module_scope)
